<?php
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();

$logoSizeResolver = $block->getLogoSizeResolver();
$logoWidth = $logoSizeResolver !== null && $logoSizeResolver->getWidth()
    ? $logoSizeResolver->getWidth()
    : $block->getLogoWidth();
$logoHeight = $logoSizeResolver !== null && $logoSizeResolver->getHeight()
    ? $logoSizeResolver->getHeight()
    : $block->getLogoHeight();
?>

<a
    class="logo"
    href="<?= $block->escapeUrl($block->getUrl('')) ?>"
    title="<?= $block->escapeHtmlAttr($storeName) ?>"
    aria-label="store logo">
    <img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
         title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
         <?= $logoWidth ? 'width="' . $block->escapeHtmlAttr($logoWidth) . '"' : '' ?>
         <?= $logoHeight ? 'height="' . $block->escapeHtmlAttr($logoHeight) . '"' : '' ?>
    />
</a>
