<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)): ?>
    <div class="breadcrumb bdcrum bg_white">
        <div class="main_container">
            <ul class="items bdcrum_list">
                <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
                    <li class="item bdcrum_item <?= $block->escapeHtmlAttr($crumbName) ?>">
                        <?php if ($crumbInfo['link']): ?>
                            <a class="bdcrum_link" href="<?= $block->escapeUrl($crumbInfo['link']) ?>"
                                title="<?= $block->escapeHtml($crumbInfo['title']) ?>">
                                <?= $block->escapeHtml($crumbInfo['label']) ?>
                            </a>
                        <?php elseif ($crumbInfo['last']): ?>
                            <strong class="bdcrum_link"><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
                        <?php else: ?>
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>